/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duoc.cl.hoytsmarkplanet.Views;

/**
 *
 * @author cetecom
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtBienvenido = new javax.swing.JLabel();
        txtEncabezado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        agregarPelicula = new javax.swing.JMenuItem();
        editarPelicula = new javax.swing.JMenuItem();
        eliminarPelicula = new javax.swing.JMenuItem();
        listarPeliculas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jDesktopPane1.setLayout(new java.awt.GridBagLayout());

        txtBienvenido.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        txtBienvenido.setText("¡Bienvenido a HoytsMarkPlanet!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(36, 35, 36, 35);
        jDesktopPane1.add(txtBienvenido, gridBagConstraints);

        txtEncabezado.setText("Selecciona alguna de las opciones del menú");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(38, 36, 36, 36);
        jDesktopPane1.add(txtEncabezado, gridBagConstraints);

        jMenu1.setText("Opciones");

        agregarPelicula.setText("Agregar Película");
        agregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(agregarPelicula);

        editarPelicula.setText("Editar Película");
        editarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(editarPelicula);

        eliminarPelicula.setText("Eliminar Película");
        eliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarPelicula);

        listarPeliculas.setText("Listar Películas");
        listarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(listarPeliculas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPeliculaActionPerformed
    
        AgregarPelicula ventanaAgregar = new AgregarPelicula();
        ventanaAgregar.setVisible(true);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(ventanaAgregar);
        this.pack();
        
    }//GEN-LAST:event_agregarPeliculaActionPerformed

    private void editarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPeliculaActionPerformed
        EditarPelicula edit = new EditarPelicula();
        edit.setVisible(true);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(edit);
        this.pack();
    }//GEN-LAST:event_editarPeliculaActionPerformed

    private void eliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPeliculaActionPerformed
        EliminarPelicula elim = new EliminarPelicula();
        elim.setVisible(true);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(elim);
        this.pack();
    }//GEN-LAST:event_eliminarPeliculaActionPerformed

    private void listarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPeliculasActionPerformed
        ListarPelicula list = new ListarPelicula();
        list.setVisible(true);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(list);
        this.pack();
    }//GEN-LAST:event_listarPeliculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarPelicula;
    private javax.swing.JMenuItem editarPelicula;
    private javax.swing.JMenuItem eliminarPelicula;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarPeliculas;
    private javax.swing.JLabel txtBienvenido;
    private javax.swing.JLabel txtEncabezado;
    // End of variables declaration//GEN-END:variables
}
